server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_productos?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: "" 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

example:
  property: "Hola al Magister Coba un saludo cordial pongame 10"
